import Foundation

/// Verbatim hard-coded safety strings per SAFETY_DISCLAIMERS.md.
///
/// NEVER re-type these strings in any View.
/// Always reference `HardCodedStrings.userDisclaimer` / `.heatEmergencyText`.
///
/// RULES_CONSTANTS_V1 §H.2: these strings must NOT be generated by the LLM.
/// They are compiled into the app. Changes require a version bump per §J.
enum HardCodedStrings {

    // MARK: - §A: User-Facing Disclaimer
    // Source: SAFETY_DISCLAIMERS.md §A (verbatim)
    static let userDisclaimer = """
    This app provides general tournament preparation guidance. It is not medical advice, nutrition therapy, or a substitute for a coach, physician, athletic trainer, or registered dietitian. For injuries, illness, heat symptoms, allergies, eating disorders, or medical conditions, consult a qualified professional.
    """

    // MARK: - §B: Heat Emergency Guidance
    // Source: SAFETY_DISCLAIMERS.md §B (verbatim)
    // ⚠️ DRAFT — OQ-11: Wording is pending attorney review before App Store submission.
    //    DO NOT treat this wording as legally cleared. Pre-launch blocker.
    static let heatEmergencyText = """
    If the player feels faint, confused, has chest pain, stops sweating in extreme heat, has severe cramps, vomits repeatedly, or shows signs of heat illness, stop play and seek medical help immediately.
    """

    // MARK: - §H.1: Overrun Message
    // Source: RULES_CONSTANTS_V1 §H.1 (verbatim)
    static let overrunMessage = """
    Match 1 may not finish before Match 2's estimated start time. Alert the tournament desk.
    """

    // MARK: - §H.3: Bag Food Fallback
    // Source: RULES_CONSTANTS_V1 §H.3 (verbatim)
    static let bagFoodFallback = """
    Use immediate bag food only: banana, pretzels, applesauce pouch, electrolyte drink, simple sandwich if tolerated.
    """
}
