import Foundation

/// Verbatim hard-coded safety strings per SAFETY_DISCLAIMERS.md.
///
/// NEVER re-type these strings in any View.
/// Always reference `HardCodedStrings.userDisclaimer` / `.heatEmergencyText`.
///
/// RULES_CONSTANTS_V1 §H.2: these strings must NOT be generated by the LLM.
/// They are compiled into the app. Changes require a version bump per §J.
enum HardCodedStrings {

    // MARK: - §A: User-Facing Disclaimer
    // Source: SAFETY_DISCLAIMERS.md §A (verbatim)
    static let userDisclaimer = """
    This app provides general tournament preparation guidance. It is not medical advice, nutrition therapy, or a substitute for a coach, physician, athletic trainer, or registered dietitian. For injuries, illness, heat symptoms, allergies, eating disorders, or medical conditions, consult a qualified professional.
    """

    // MARK: - §B: Heat Emergency Guidance
    // Source: SAFETY_DISCLAIMERS.md §B v1.1 (revised 2026-04-27 per OQ-11 / TRIAGE_2026-04-27.md)
    // ⚠️ Pending legal sign-off (OQ-06). Do not treat wording as legally cleared
    //    before App Store submission. Surface ONLY through this constant.
    // v1.1 wording from SAFETY_DISCLAIMERS.md §B; pending legal sign-off (OQ-06)
    static let heatEmergencyText = """
    If your player feels faint or confused, has chest pain, stops sweating in extreme heat, has severe cramps, vomits repeatedly, or shows signs of heat illness: stop play and seek medical help. Call 911 (or your local emergency number) in an emergency.
    """

    // MARK: - §H.1: Overrun Message
    // Source: RULES_CONSTANTS_V1 §H.1 (verbatim)
    static let overrunMessage = """
    Match 1 may not finish before Match 2's estimated start time. Alert the tournament desk.
    """

    // MARK: - §H.3: Bag Food Fallback
    // Source: RULES_CONSTANTS_V1 §H.3 (verbatim)
    static let bagFoodFallback = """
    Use immediate bag food only: banana, pretzels, applesauce pouch, electrolyte drink, simple sandwich if tolerated.
    """
}
