"""LLM provider abstraction — Phase 6 / Task #9.

Mirrors the structure of services/places.py (Provider Protocol + two concrete
implementations + factory gated on env vars).

Provider selection (settings.LLM_PROVIDER):
    "auto"       → AnthropicProvider if ANTHROPIC_API_KEY set, else
                   OpenAIProvider if OPENAI_API_KEY set, else TemplateProvider.
    "template"   → TemplateProvider always (deterministic, no network, used in tests + demo).
    "anthropic"  → AnthropicProvider (key required; NotImplementedError if SDK missing).
    "openai"     → OpenAIProvider     (key required; NotImplementedError if SDK missing).

The Dallas demo works end-to-end with TemplateProvider — no API keys required.
Real LLM providers are stubs (SDK not in pyproject.toml); they raise a clear
NotImplementedError when instantiated without the SDK installed.

Non-negotiable safety principle (PRD §2 / PLAN.md §2):
    The LLM converts structured JSON into parent-friendly language.
    It NEVER invents restaurants, menu items, medical advice, or schedule logic.
    All real-provider output is wrapped in sanitize_or_fallback() before returning.
"""
from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from typing import Optional, Protocol

from playfuel_api.rules.duration_format import friendly_duration

_logger = logging.getLogger(__name__)

# ── SAFETY_DISCLAIMERS.md §E — verbatim system prompt for real LLM providers ──

SYSTEM_PROMPT: str = (
    "You are a junior tennis tournament assistant.\n\n"
    "You will receive a structured plan generated by our rules engine.\n\n"
    "Your job:\n"
    "- Explain the plan clearly to a parent.\n"
    "- Use a calm, practical tone.\n"
    "- Do not invent restaurants, menu items, weather facts, match rules, or medical advice.\n"
    "- Do not change the structured timing.\n"
    "- Mention that injury or illness concerns should be handled by a qualified professional.\n"
    "- Keep the plan concise enough to read during a tournament.\n\n"
    "Structured plan:\n{{PLAN_JSON}}"
)


# ── Protocol (structural interface) ───────────────────────────────────────────


class LLMProvider(Protocol):
    """Structural interface for LLM explanation backends."""

    def explain_plan(
        self,
        plan_input: "PlanExplanationInput",  # noqa: F821
    ) -> "PlanExplanation":  # noqa: F821
        ...


# ── TemplateProvider (deterministic, no network) ──────────────────────────────


def _fmt_iso_to_display(iso: str) -> str:
    """Parse ISO 8601 datetime string → 'Saturday at 9:00 AM' style.

    Handles both naive and timezone-aware strings. Falls back to raw string
    if parsing fails.
    """
    try:
        clean = iso.replace("Z", "+00:00")
        dt = datetime.fromisoformat(clean)
        day = dt.strftime("%A")
        h = dt.hour % 12 or 12
        ampm = "AM" if dt.hour < 12 else "PM"
        return f"{day} at {h}:{dt.minute:02d} {ampm}"
    except Exception:  # noqa: BLE001
        return iso


def _gap_status_text(gap_status: str) -> str:
    """Convert gap_status value to a parent-friendly phrase."""
    return {
        "ok": "comfortable break",
        "tight": "tight turnaround",
        "overrun": "potential schedule overrun",
        "no_next_match": "no next match today",
    }.get(gap_status, gap_status)


def _food_bucket_guidance(food_bucket: Optional[str]) -> str:
    """Convert food_bucket value to a parent-friendly guidance phrase."""
    if food_bucket is None:
        return "follow your normal post-match routine"
    return {
        "bag_only": "use bag food only—banana, pretzels, electrolyte drink",
        "portable": "grab portable pre-bought food quickly after the match ends",
        "quick_pickup": "pick up a quick fast-casual meal during the break",
        "light_meal": "there is time for a light meal—avoid heavy or greasy foods",
    }.get(food_bucket, "follow your normal post-match routine")


def _pickup_bucket_text(pickup_bucket: str) -> str:
    """Convert pickup_bucket value to a parent-friendly phrase."""
    return {
        "bring_portable": "have portable food ready before the match ends",
        "pickup_during_match": "consider picking up food during the final portion of the match if another trusted adult is present",
        "wait_until_end": "wait until the match ends before getting food",
    }.get(pickup_bucket, "follow your normal routine")


class TemplateProvider:
    """Deterministic template-based explanation provider.

    Used by default (no API keys required) and in all tests. Generates
    parent-friendly prose via f-strings — never invents content. Every field
    in the output comes directly from PlanExplanationInput.

    Returns PlanExplanation with provider='template', model=None.
    """

    def explain_plan(
        self,
        inp: "PlanExplanationInput",  # noqa: F821
    ) -> "PlanExplanation":  # noqa: F821
        from playfuel_api.models.api import PlanExplanation

        return PlanExplanation(
            summary=self._build_summary(inp),
            scenario_explanations=self._build_scenario_explanations(inp),
            weather_note=self._build_weather_note(inp),
            food_note=self._build_food_note(inp),
            safety_note=self._build_safety_note(inp),
            provider="template",
            model=None,
            generated_at=datetime.now(tz=timezone.utc),
        )

    # MARK: - Internal builders (all pure functions of inp — no invented content)

    @staticmethod
    def _build_summary(inp: "PlanExplanationInput") -> str:  # noqa: F821
        venue = inp.venue_name or "the venue"
        round_part = f"a {inp.match_round_label} match" if inp.match_round_label else "a match"
        time_part = _fmt_iso_to_display(inp.match_start_iso)
        heat_note = " Extreme heat conditions are expected today." if inp.extreme_heat_risk else ""
        is_doubles = getattr(inp, "match_type", "singles") == "doubles"

        # Derive normal-scenario duration from scenarios (avoids hardcoding 120 min).
        normal_s = next((s for s in inp.scenarios if s.scenario == "normal"), None)
        normal_min = normal_s.duration_min if normal_s else (90 if is_doubles else 120)

        if is_doubles:
            subject = "Your child's doubles team"
            match_desc = f"{round_part}"
        else:
            subject = "Your player's tournament day"
            match_desc = f"includes {round_part}"

        summary = (
            f"{subject} at {venue} {match_desc} "
            f"scheduled to start at {time_part}. "
            f"We've prepared three scenarios—short, normal, and long—to cover "
            f"different match durations. "
            f"The normal scenario (~{friendly_duration(normal_min)}) is used as the primary planning reference."
            f"{heat_note}"
        )

        # Conservative opponent-notes acknowledgment (PLAYER_SCOUTING_V1.md §D.4).
        # Count-only: never quotes note body, never reveals source.
        # Real tactical paraphrase waits for actual LLM provider — OQ-SCOUT-LLM-1.
        notes = getattr(inp, "opponent_notes", [])
        if notes:
            n = len(notes)
            word = "observation" if n == 1 else "observations"
            summary += (
                f" Your notes mention {n} prior {word}"
                f" — review the player profile for tactics."
            )

        return summary

    @staticmethod
    def _build_scenario_explanations(
        inp: "PlanExplanationInput",  # noqa: F821
    ) -> dict[str, str]:
        is_doubles = getattr(inp, "match_type", "singles") == "doubles"
        subject = "your doubles team" if is_doubles else "you"
        result: dict[str, str] = {}
        for s in inp.scenarios:
            gap = _gap_status_text(s.gap_status)
            food = _food_bucket_guidance(s.food_bucket)
            pickup = _pickup_bucket_text(s.pickup_bucket)
            result[s.scenario] = (
                f"In the {s.scenario} scenario ({friendly_duration(s.duration_min)} match): "
                f"{subject}'ll have a {gap}. "
                f"For food: {food}. "
                f"For parent pickup: {pickup}."
            )
        return result

    @staticmethod
    def _build_weather_note(
        inp: "PlanExplanationInput",  # noqa: F821
    ) -> Optional[str]:
        if inp.weather_temp_f is None:
            return None

        humidity_str = ""
        if inp.weather_humidity_pct is not None:
            humidity_str = f" with {inp.weather_humidity_pct}% humidity"

        flag_note = ""
        if "very_hot" in inp.weather_flags:
            flag_note = " Keep the player in shade and ensure extra fluids are available between points."
        elif "hot" in inp.weather_flags:
            flag_note = " Keep the player cool with shade and extra fluids during breaks."
        elif "cold" in inp.weather_flags:
            flag_note = " Ensure the player stays warm between matches."

        rain_note = ""
        if "rain_risk" in inp.weather_flags:
            rain_note = " There is a chance of rain—bring a rain plan and extra dry clothes."

        return (
            f"Today's conditions are {inp.weather_temp_f:.0f}°F{humidity_str}."
            f"{flag_note}{rain_note}"
        ).strip()

    @staticmethod
    def _build_food_note(
        inp: "PlanExplanationInput",  # noqa: F821
    ) -> Optional[str]:
        if inp.bag_fallback_only:
            return "Pack from home \u2014 bag-only window between matches."
        if not inp.food_recommendations:
            return None
        top3 = inp.food_recommendations[:3]
        parts: list[str] = []
        for r in top3:
            drive = f", {r.drive_time_minutes} min drive" if r.drive_time_minutes is not None else ""
            parts.append(f"{r.name} ({r.category}{drive})")
        return f"Nearby options: {', '.join(parts)}."

    @staticmethod
    def _build_safety_note(
        inp: "PlanExplanationInput",  # noqa: F821
    ) -> str:
        if inp.extreme_heat_risk and inp.heat_emergency_text:
            return f"{inp.heat_emergency_text}\n\n{inp.user_disclaimer}"
        return inp.user_disclaimer


# ── AnthropicProvider (stub — SDK not in pyproject.toml) ─────────────────────


class AnthropicProvider:
    """Anthropic Messages API provider (stub — implementation deferred).

    Gated on settings.ANTHROPIC_API_KEY. Performs a soft-import of the
    `anthropic` SDK inside __init__ — if the SDK is not installed, raises
    NotImplementedError with a clear install message.

    All output is wrapped in sanitize_or_fallback() before returning, so
    safety guarantees hold even if the LLM produces unexpected text.
    """

    def __init__(self, api_key: str, model: str) -> None:
        try:
            import anthropic  # type: ignore[import]
            self._anthropic = anthropic
        except ImportError as exc:
            raise NotImplementedError(
                "AnthropicProvider requires the 'anthropic' SDK. "
                "Install it with: pip install anthropic. "
                "Or set LLM_PROVIDER=template to use the deterministic fallback."
            ) from exc
        self._api_key = api_key
        self._model = model

    def explain_plan(
        self,
        inp: "PlanExplanationInput",  # noqa: F821
    ) -> "PlanExplanation":  # noqa: F821
        from playfuel_api.services.llm_safety import sanitize_or_fallback

        # Stub: real implementation calls self._anthropic.Anthropic(api_key=...).messages.create(...)
        # with SYSTEM_PROMPT and inp.model_dump(mode='json') as the plan payload.
        # Returns sanitize_or_fallback(parsed_response, inp).
        raise NotImplementedError(
            "AnthropicProvider.explain_plan() is a stub (OQ-LLM-1). "
            "Set LLM_PROVIDER=template to use the deterministic TemplateProvider."
        )


# ── OpenAIProvider (stub — SDK not in pyproject.toml) ────────────────────────


class OpenAIProvider:
    """OpenAI Responses API provider (stub — implementation deferred).

    Same structure as AnthropicProvider. Gated on settings.OPENAI_API_KEY.
    Soft-imports the `openai` SDK — raises NotImplementedError if not installed.
    """

    def __init__(self, api_key: str, model: str) -> None:
        try:
            import openai  # type: ignore[import]
            self._openai = openai
        except ImportError as exc:
            raise NotImplementedError(
                "OpenAIProvider requires the 'openai' SDK. "
                "Install it with: pip install openai. "
                "Or set LLM_PROVIDER=template to use the deterministic fallback."
            ) from exc
        self._api_key = api_key
        self._model = model

    def explain_plan(
        self,
        inp: "PlanExplanationInput",  # noqa: F821
    ) -> "PlanExplanation":  # noqa: F821
        from playfuel_api.services.llm_safety import sanitize_or_fallback

        raise NotImplementedError(
            "OpenAIProvider.explain_plan() is a stub (OQ-LLM-2). "
            "Set LLM_PROVIDER=template to use the deterministic TemplateProvider."
        )


# ── Factory ───────────────────────────────────────────────────────────────────


def get_llm_provider() -> LLMProvider:
    """Return the configured LLM provider.

    Provider selection:
        "auto"      → Anthropic if ANTHROPIC_API_KEY non-empty, else
                      OpenAI if OPENAI_API_KEY non-empty, else TemplateProvider.
        "template"  → TemplateProvider always.
        "anthropic" → AnthropicProvider (raises NotImplementedError if SDK missing).
        "openai"    → OpenAIProvider    (raises NotImplementedError if SDK missing).

    Never raises in 'auto' mode — always falls back to TemplateProvider.
    """
    from playfuel_api.settings import get_settings

    settings = get_settings()
    provider_name = settings.llm_provider.lower()

    if provider_name == "template":
        return TemplateProvider()

    if provider_name == "anthropic":
        return AnthropicProvider(
            api_key=settings.anthropic_api_key,
            model=settings.anthropic_model,
        )

    if provider_name == "openai":
        return OpenAIProvider(
            api_key=settings.openai_api_key,
            model=settings.openai_model,
        )

    # "auto" or unrecognised → first available key, else TemplateProvider
    if settings.anthropic_api_key:
        try:
            return AnthropicProvider(
                api_key=settings.anthropic_api_key,
                model=settings.anthropic_model,
            )
        except NotImplementedError:
            _logger.warning(
                "AnthropicProvider unavailable (SDK not installed). "
                "Falling back to TemplateProvider."
            )

    if settings.openai_api_key:
        try:
            return OpenAIProvider(
                api_key=settings.openai_api_key,
                model=settings.openai_model,
            )
        except NotImplementedError:
            _logger.warning(
                "OpenAIProvider unavailable (SDK not installed). "
                "Falling back to TemplateProvider."
            )

    return TemplateProvider()


# ── build_explanation_input ────────────────────────────────────────────────────


def build_explanation_input(
    plan: "Plan",  # noqa: F821
    match: "MatchRow",  # noqa: F821
    next_match: "Optional[MatchRow]",  # noqa: F821
    snapshot: "Optional[WeatherSnapshotRow]",  # noqa: F821
    food_options_list: "list[FoodOption]",  # noqa: F821
    venue_name: str = "",
) -> "PlanExplanationInput":  # noqa: F821
    """Build a PlanExplanationInput from the assembled plan and raw components.

    Every field is derived from structured inputs — nothing is invented.
    Called in routes/plans.py after build_plan_envelope() returns.
    """
    from playfuel_api.models.api import (
        FoodRecommendationSummary,
        PlanExplanationInput,
        ScenarioSummary,
    )
    from playfuel_api.rules.hard_coded_strings import HEAT_EMERGENCY_TEXT, USER_DISCLAIMER

    # Scenarios
    scenarios = [
        ScenarioSummary(
            scenario=s.scenario.value,
            duration_min=s.duration_min,
            gap_status=s.gap_status.value,
            food_bucket=s.food_strategy.bucket.value if s.food_strategy else None,
            pickup_bucket=(
                s.pickup_strategy.bucket.value
                if s.pickup_strategy and s.pickup_strategy.bucket
                else "wait_until_end"
            ),
        )
        for s in plan.scenario_plans
    ]

    # Food recommendations (name + category + drive_time; no address / place_id)
    food_recs = [
        FoodRecommendationSummary(
            name=f.name,
            category=f.category,
            drive_time_minutes=f.drive_time_minutes,
            is_draft=f.is_draft if hasattr(f, "is_draft") else False,
        )
        for f in (food_options_list or [])
    ]

    # Weather flags
    weather_flags: list[str] = []
    weather_temp_f: Optional[float] = None
    weather_humidity_pct: Optional[int] = None
    extreme_heat_risk = False
    if snapshot is not None:
        weather_temp_f = snapshot.temp_f
        weather_humidity_pct = int(snapshot.humidity_pct)
        if snapshot.flag_hot:
            weather_flags.append("hot")
        if snapshot.flag_very_hot:
            weather_flags.append("very_hot")
        if snapshot.flag_humid:
            weather_flags.append("humid")
        if snapshot.flag_cold:
            weather_flags.append("cold")
        if snapshot.flag_windy:
            weather_flags.append("windy")
        if snapshot.flag_rain_risk:
            weather_flags.append("rain_risk")
        extreme_heat_risk = snapshot.flag_extreme_heat_risk

    # Derive match_type from match.format (doubles-spec §C.2).
    match_type_val = (match.format or "singles").lower()
    if match_type_val not in ("singles", "doubles"):
        match_type_val = "singles"

    return PlanExplanationInput(
        venue_name=venue_name,
        match_start_iso=match.scheduled_start.isoformat(),
        match_round_label=match.round_label,
        next_match_estimated_iso=(
            next_match.scheduled_start.isoformat() if next_match else None
        ),
        weather_temp_f=weather_temp_f,
        weather_humidity_pct=weather_humidity_pct,
        weather_flags=weather_flags,
        extreme_heat_risk=extreme_heat_risk,
        scenarios=scenarios,
        food_recommendations=food_recs,
        bag_fallback_only=plan.bag_fallback_only,
        heat_emergency_text=HEAT_EMERGENCY_TEXT if extreme_heat_risk else None,
        user_disclaimer=USER_DISCLAIMER,
        match_type=match_type_val,
    )
